spring:
  application:
    name: worldbuy-search
  cloud:
    nacos:
      discovery:
        server-addr: 34.105.136.131:8848
  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/

ipAddr: 34.105.136.131
server:
  port: 12000
