spring:
  cloud:
    nacos:
      discovery:
        server-addr: 34.105.136.131:8848
    alicloud:
      access-key: LTAI5tJXsFTuitJfk31skKLx
      secret-key: ctk4evgIiquiDrajJ1bXDuXXOxtnYF
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: mall-lxj

  application:
    name: worldbuy-third-party

server:
  port: 30000