spring:
  cloud:
    nacos:
      discovery:
        server-addr: 34.105.136.131:8848
    alicloud:
      access-key: LTAI5tJXsFTuitJfk31skKLx
      secret-key: ctk4evgIiquiDrajJ1bXDuXXOxtnYF
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: mall-lxj
  ali:
    sms:
      host: https://dfsns.market.alicloudapi.com
      path: /data/send_sms
      method: POST
      appcode: 439775fc63fb4b5d8501c60e69436e55

  application:
    name: worldbuy-third-party

server:
  port: 30000