ipAddr: 127.0.0.1
spring:
  application:
    name: worldbuy-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 34.105.136.131:8848
#    sentinel:
#      transport:
#        dashboard: localhost:8333
  thymeleaf:
    cache: false
  session:
    store-type: redis
  redis:
    host: ${ipAddr}
    port: 6379
server:
  port: 20000
  # session存活时间
#  servlet:
#    session:
#      timeout: 30m