server:
  port: 11001
spring:
  datasource:
    username: root
    password: DTMKlxj199866
    url: jdbc:mysql://34.105.136.131:3306/worldbuy_wms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 34.105.136.131:8848
  application:
    name: worldbuy-ware
#    sentinel:
#      transport:
#        dashboard: localhost:8333
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  rabbitmq:
    host: 34.105.136.131
#    port: 5672
    # 指定虚拟主机
    virtual-host: /
#    username: guest
#    password: guest
    listener:
      simple:
        # 手动确认接受消息
        acknowledge-mode: manual
#  zipkin:
#    base-url: 10.43.1.52:9411/
#    # 关闭我们自动的服务发现功能
#    discovery-client-enabled: false
#    sender:
#      type: web
#  sleuth:
#    sampler:
#      probability: 1
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
#logging:
#  level:
#    com.mall.ware: debug
myRabbitmq:
  MQConfig:
    queues: stock.release.stock.queue
    delayQueue: stock.delay.queue
    eventExchange: stock-event-exchange
    routingKey: stock.locked
    letterRoutingKey: stock.release
    # 库存自动过期时间 单位:(毫秒)
    ttl: 900000