spring:
  cloud:
    gateway:
      routes:
        - id: product_route
          uri: lb://worldbuy-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        - id: coupon_route
          uri: lb://worldbuy-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        - id: member_route
          uri: lb://worldbuy-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        - id: ware_route
          uri: lb://worldbuy-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        #  OSS
        - id: third_party_route
          uri: lb://worldbuy-third-party
          predicates:
            - Path=/api/third/party/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*), /renren-fast/$\{segment}
        - id: search_route
          uri: lb://worldbuy-search
          predicates:
            - Host=search.worldbuy.com
        - id: mall_route
          uri: lb://worldbuy-product
          predicates:
            - Host=**.worldbuy.com,worldbuy.com,item.worldbuy.com
