server:
  port: 15001
spring:
#    sentinel:
#      transport:
#        dashboard: localhost:8333
  datasource:
    username: root
    password: DTMKlxj199866
    url: jdbc:mysql://34.105.136.131:3306/worldbuy_oms
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  cloud:
    nacos:
      discovery:
        server-addr: 34.105.136.131:8848
  application:
    name: worldbuy-order
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
  rabbitmq:
    host: 34.105.136.131
    port: 5672
    # 指定虚拟主机
    virtual-host: /
    username: guest
    password: guest
    # 开启发送端确认
    publisher-confirms: true
    #　开启发送端消息抵达队列确认
    publisher-returns: true
    # 只要抵达队列，以异步优先回调我们这个 returnconfirm
    template:
      mandatory: true
    # 手动ack消息 消息不容易丢失
    listener:
      simple:
        acknowledge-mode: manual
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
#  zipkin:
#    base-url: 34.105.136.131:9411/
#    # 关闭我们自动的服务发现功能
#    discovery-client-enabled: false
#    sender:
#      type: web
#  sleuth:
#    sampler:
#      probability: 1
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
myRabbitmq:
  queue: mall-queue
  exchange: mall-exchange
  routeKey: mall
  MQConfig:
    # 订单队列
    queues: order.release.order.queue
    delayQueue: order.delay.queue
    eventExchange: order-event-exchange
    routingKey: order.release.order
    createOrder: order.create.order
    # 订单自动过期时间 单位:(毫秒)
    ttl: 900000
    # 库存解锁队列
    ReleaseOther: stock.release.stock.queue
    ReleaseOtherKey: order.release.other
worldbuy:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10
alipay:
  app_id: 2021000121646820
  # 支付宝异步回调通知 这个来感应订单是否完成
  notify_url: https://607a-5-151-139-59.eu.ngrok.io/payed/notify
  return_url: http://member.worldbuy.com/memberOrder.html
  timeout: 15m