ipAddr: 127.0.0.1
spring:
  application:
    name: worldbuy-cart
  cloud:
    nacos:
      discovery:
        server-addr: 34.105.136.131:8848
#    sentinel:
#      transport:
#        dashboard: localhost:8333
  session:
    store-type: redis
  redis:
    host: ${ipAddr}
server:
  port: 40000
worldbuy:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10